name: torch-haskell-CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up GHC & Cabal
        uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.12.2"
          cabal-version: "3.12.1.0"

      - name: Cache cabal
        uses: actions/cache@v4
        with:
          path: |
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-ghc-9.12.2-${{ hashFiles('**/*.cabal', 'cabal.project*') }}
          restore-keys: |
            ${{ runner.os }}-ghc-9.12.2-

      - name: Cabal update
        run: cabal update

      - name: Set up HLint
        uses: haskell-actions/hlint-setup@v2

      - name: Lint (hlint)
        uses: haskell-actions/hlint-run@v2
        with:
          path: .
          fail-on: warning

      - name: Format check (Fourmolu)
        uses: haskell-actions/run-fourmolu@v9
        with:
          version: "0.13.0.0"

      - name: Build
        run: cabal build all --enable-tests --ghc-options="-Wall -Werror" -j

      - name: Test
        run: cabal test all --enable-tests --test-show-details=direct -j
